I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/options.rpy", line 21, in script
    define gui.show_name = false
  File "game/options.rpy", line 21, in <module>
    define gui.show_name = false
NameError: name 'false' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/options.rpy", line 21, in script
    define gui.show_name = false
  File "/Users/rhythm0708/Desktop/renpy-8.3.7-sdk/renpy/ast.py", line 2248, in execute
    self.set()
  File "/Users/rhythm0708/Desktop/renpy-8.3.7-sdk/renpy/ast.py", line 2262, in set
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "/Users/rhythm0708/Desktop/renpy-8.3.7-sdk/renpy/python.py", line 1211, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/options.rpy", line 21, in <module>
    define gui.show_name = false
NameError: name 'false' is not defined

macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.3.7.25031702
AI Hiring Edition 1.0
Fri Jun 20 15:27:56 2025
